/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Usuario;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Jonathan Alexis Sanchez Rodriguez
 */
public class FrmBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form FrmBienvenida
     */
    
    private Usuario u;
    
    public FrmBienvenida(Usuario usuario) {
        this.u = usuario;
        initComponents();
        cargarContenido(u); 
        configurarVentana();
        
    }
    
    private void cargarContenido(Usuario u){
        JPanel panel = new JPanel(new BorderLayout(20, 20));
    panel.setBackground(new Color(235, 245, 255));
    panel.setBorder(BorderFactory.createEmptyBorder(30, 40, 30, 40));
    
    JLabel lblFoto = new JLabel ();
    lblFoto.setHorizontalAlignment(SwingConstants.CENTER);
    lblFoto.setPreferredSize(new Dimension(120,120));
    lblFoto.setBorder(BorderFactory.createLineBorder(new Color (0, 150, 160), 2 ));
    lblFoto.setBackground(Color.WHITE);
    lblFoto.setOpaque(true);
    
    if (u.getFoto() != null && u.getFoto().length > 0 ){
        ImageIcon icon = new ImageIcon(u.getFoto());
        Image escalada = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        lblFoto.setIcon(new ImageIcon(escalada));
    }else{
        
        lblFoto.setText("sin foto");
    }

    JPanel panelTexto = new JPanel();
    panelTexto.setOpaque(false);
    panelTexto.setLayout(new BoxLayout(panelTexto, BoxLayout.Y_AXIS));

    JLabel lblBienvenida = new JLabel("¡Bienvenido al Sistema!");
    lblBienvenida.setFont(new Font("Arial", Font.BOLD, 20));
    lblBienvenida.setForeground(new Color(31, 78, 121));
    lblBienvenida.setAlignmentX(Component.CENTER_ALIGNMENT);

    JLabel lblNombre = new JLabel(u.getNombre() + " " + u.getApellido());
    lblNombre.setAlignmentX(Component.CENTER_ALIGNMENT);

    JLabel lblUsuario = new JLabel("Usuario: " + u.getUsuario());
    lblUsuario.setAlignmentX(Component.CENTER_ALIGNMENT);

    panelTexto.add(lblBienvenida);
    panelTexto.add(lblNombre);
    panelTexto.add(lblUsuario);

    JButton btnSalir = new JButton("Cerrar Sesión");
btnSalir.addActionListener((ActionEvent e) -> {
            new FrmLogin().setVisible(true);
            this.dispose();
        });
    panel.add(lblFoto, BorderLayout.WEST);
    panel.add(panelTexto, BorderLayout.CENTER);
    panel.add(btnSalir, BorderLayout.SOUTH);

    getContentPane().setLayout(new BorderLayout());
    getContentPane().add(panel, BorderLayout.CENTER);

    revalidate();
    repaint();
    }
    
    private void configurarVentana() {
        setTitle("Bienvenida");
        setSize(480, 280);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // 1. Creamos un usuario de prueba (asegúrate de que los datos coincidan con tu clase Usuario)
    modelo.Usuario usuarioPrueba = new modelo.Usuario();
    usuarioPrueba.setNombre("Nombre");
    usuarioPrueba.setApellido("Apellido");
    usuarioPrueba.setUsuario("admin");
    // Si tienes un método para asignar imagen, hazlo aquí, si no, saldrá "Sin foto"

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // 2. Pasamos el usuario de prueba al constructor
            new FrmBienvenida(usuarioPrueba).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
